### PR TITLE
create and connect light generation

### PR DESCRIPTION
**Pull request by grezisek1**

### CODE REVIEW

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
## Code Review Report

### Task goal
Connect previously created components, and implement logic for displaying light components based on rows counter, and columns counter values.

### Requirements
1. The components for rows and columns counter, and single light should be connected and integrated into a larger application.
2. The amount of columns should not be higher than 9.
3. The application should have logic that uses the values from the rows counter and columns counter components to determine the number of lights to display in the dynamic grid.

### Code Changes Review

#### src/App.css
The changes in this file are correct. The `grid-template-columns` property is now using a CSS variable `--cols` to dynamically set the number of columns, which aligns with requirement 3.

#### src/App.jsx
The changes in this file cover all the requirements.

1. The `NumberInput` and `Light` components are connected and integrated into the larger application, which meets requirement 1.
2. The `increment` function now has a condition that prevents the `columns` value from exceeding 9, which meets requirement 2.
3. The application now uses the values from the `rows` and `columns` counters to determine the number of `Light` components to display in the grid. This is done by creating an array of `Light` components based on the product of `rows` and `columns`, which meets requirement 3.

However, there is a potential issue with the `lights` array. It's defined outside of the `App` function, which means it's not part of the component's state and won't trigger a re-render when it changes. This could lead to unexpected behavior. It would be better to move this logic inside the `App` function and use the `useState` hook to manage it.

Here's an example of how you could do this:

```jsx
export default function App() {
  [size, setSize] = useState(defaultState);
  const count = size.rows * size.columns;
  const [lights, setLights] = useState(Array(count).fill(<Light color={"yellow"} />));

  useEffect(() => {
    setLights(Array(count).fill(<Light color={"yellow"} />));
  }, [count]);

  // ...
}
```

This way, the `lights` array will be part of the component's state and will trigger a re-render when it changes. The `useEffect` hook is used to update the `lights` array whenever the `count` changes.

**Comment by grezisek1** [comment]
> It's defined outside of the App function, which means it's not part of the component's state and won't trigger a re-render when it changes.

and it should not - it changes because of the state change. that state change triggers a re-render. no need to do it twice

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
## Code Review Report

### Task Goal
Connect previously created components, and implement logic for displaying light components based on rows counter, and columns counter values.

### Requirements
1. The components for rows and columns counter, and single light should be connected and integrated into a larger application.
2. The amount of columns should not be higher than 9.
3. The application should have logic that uses the values from the rows counter and columns counter components to determine the number of lights to display in the dynamic grid.

### Code Changes Review

#### src/App.css
The change in this file is correct and meets the requirements. The number of columns is now a variable (`--cols`) which can be dynamically set in the component's style.

#### src/App.jsx
The changes in this file also meet the requirements. 

1. The components are connected and integrated into the larger application. The `NumberInput` components for rows and columns are used to control the number of lights displayed in the grid.

2. The amount of columns is restricted to not be higher than 9. This is done in the `increment` function where it checks if the target name is "columns" and if its value is greater than 8, it returns without incrementing.

3. The application has logic to determine the number of lights to display based on the values from the rows and columns counters. This is done in the `App` function where it calculates `count` as the product of `size.rows` and `size.columns`, then uses a loop to create an array of `Light` components of length `count`.

However, there is a potential issue with this implementation. The `lights` array is defined outside of the `App` function, which means it's not part of the component's state or props. This could lead to unexpected behavior because React may not properly re-render when this array changes. 

A better approach would be to create the `lights` array inside the `App` function and use the `useEffect` hook to update it whenever `size.rows` or `size.columns` changes. Here's an example of how you could do this:

```jsx
export default function App() {
  [size, setSize] = useState(defaultState);
  const [lights, setLights] = useState([]);
  
  useEffect(() => {
    const count = size.rows * size.columns;
    const newLights = Array(count).fill(<Light color={"yellow"} />);
    setLights(newLights);
  }, [size.rows, size.columns]);

  // rest of the code...
}
```

This way, the `lights` array is part of the component's state and will trigger a re-render whenever it changes.

**Review by NerdbordMentor — APPROVED** [review]
Force approved. Hope you're not cheating!

**Pull request merged**
